2020-08-04 14:03:26,185:utils.oauth:ERROR:HTTPConnectionPool(host='nidles.ssilhr.com.pk', port=55335): Max retries exceeded with url: /core/connect/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DDE0FEB488>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-08-04 18:02:31,316:utils.oauth:ERROR:HTTPConnectionPool(host='prodqa.northeurope.cloudapp.azure.com', port=55335): Max retries exceeded with url: /core/connect/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E7B66BE448>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-08-04 18:02:59,336:utils.oauth:ERROR:HTTPConnectionPool(host='prodqa.northeurope.cloudapp.azure.com', port=55335): Max retries exceeded with url: /core/connect/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C386468EC8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2020-08-04 18:03:58,659:utils.oauth:ERROR:HTTPConnectionPool(host='prodqa.northeurope.cloudapp.azure.com', port=55335): Max retries exceeded with url: /core/connect/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026B43F4D448>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
