2021-03-01 15:12:39,210:utils.oauth:ERROR:HTTPSConnectionPool(host='pocketfactory-hbc.ssidecisions.com', port=55335): Max retries exceeded with url: /core/connect/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002229FD3CC88>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2021-03-01 16:32:32,045:utils.oauth:ERROR:HTTPSConnectionPool(host='pocketfactory-hbc.ssidecisions.com', port=55335): Max retries exceeded with url: /core/connect/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000270E0243B88>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2021-03-01 16:32:58,298:utils.oauth:ERROR:HTTPSConnectionPool(host='pocketfactory-hbc.ssidecisions.com', port=55335): Max retries exceeded with url: /core/connect/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000015EC5BC14C8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
